services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    #    restart: always
    volumes:
       - /d/docker_mysql/data/mysql:/var/lib/mysql
    command: --lower_case_table_names=1
    environment:
      MYSQL_DATABASE: ebook #创建一个初始的空数据库，名为webserver
      MYSQL_ROOT_USER: root #root用户
      MYSQL_ROOT_PASSWORD: GaoChenYuWang #root密码
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Shanghai #时区


  web:
    build: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ebook?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    container_name: web-server
#    restart: always
#    volumes:
#      - imagedata:/app/static/images/upload
    ports:
      - "8091:8091"
    depends_on:
      - mysql

#volumes:
#  dbdata:
#  imagedata:

